# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: lte.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List, Optional

import betterproto


class CellSize(betterproto.Enum):
    CELL_SIZE_UNKNOWN = 0
    CELL_SIZE_FEMTO = 1
    CELL_SIZE_ENTERPRISE = 2
    CELL_SIZE_OUTDOOR_SMALL = 3
    CELL_SIZE_MACRO = 4


@dataclass(eq=False, repr=False)
class Cell(betterproto.Message):
    """
    The Cell message defines parameters of a LTE cell that is used by various
    eSON services.
    """

    ecgi: int = betterproto.fixed64_field(1)
    cell_size: "CellSize" = betterproto.enum_field(2)
    dl_earfcn: Optional[int] = betterproto.message_field(
        3, wraps=betterproto.TYPE_UINT32
    )
    ul_earfcn: Optional[int] = betterproto.message_field(
        4, wraps=betterproto.TYPE_UINT32
    )
    pci: Optional[int] = betterproto.message_field(5, wraps=betterproto.TYPE_UINT32)
    pci_pool: "PciPool" = betterproto.message_field(100)
    neighbors: "NeighborList" = betterproto.message_field(1000)
    vendor_info: Optional[str] = betterproto.message_field(
        2000, wraps=betterproto.TYPE_STRING
    )

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class PciPool(betterproto.Message):
    """
    The PciPool message defines a set of PCI ranges. The PciService will only
    use values in this pool when allocating a new PCI.
    """

    ranges: List["PciRange"] = betterproto.message_field(1)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class PciRange(betterproto.Message):
    lower_pci: int = betterproto.uint32_field(1)
    upper_pci: int = betterproto.uint32_field(2)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class NeighborList(betterproto.Message):
    neighbors: List["Neighbor"] = betterproto.message_field(1)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class Neighbor(betterproto.Message):
    """
    The Neighbor message defines a LTE neighbor cell. It is an entry of the
    cell's neighbor table.
    """

    ecgi: int = betterproto.fixed64_field(1)
    cell_size: "CellSize" = betterproto.enum_field(2)
    dl_earfcn: Optional[int] = betterproto.message_field(
        3, wraps=betterproto.TYPE_UINT32
    )
    ul_earfcn: Optional[int] = betterproto.message_field(
        4, wraps=betterproto.TYPE_UINT32
    )
    pci: Optional[int] = betterproto.message_field(5, wraps=betterproto.TYPE_UINT32)

    def __post_init__(self) -> None:
        super().__post_init__()
