# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lte.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lte.proto',
  package='com.airhopcomm.eson.lte.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tlte.proto\x12\x1a\x63om.airhopcomm.eson.lte.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\x83\x03\n\x04\x43\x65ll\x12\x0c\n\x04\x65\x63gi\x18\x01 \x01(\x06\x12\x37\n\tcell_size\x18\x02 \x01(\x0e\x32$.com.airhopcomm.eson.lte.v1.CellSize\x12/\n\tdl_earfcn\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12/\n\tul_earfcn\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12)\n\x03pci\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12\x35\n\x08pci_pool\x18\x64 \x01(\x0b\x32#.com.airhopcomm.eson.lte.v1.PciPool\x12<\n\tneighbors\x18\xe8\x07 \x01(\x0b\x32(.com.airhopcomm.eson.lte.v1.NeighborList\x12\x32\n\x0bvendor_info\x18\xd0\x0f \x01(\x0b\x32\x1c.google.protobuf.StringValue\"?\n\x07PciPool\x12\x34\n\x06ranges\x18\x01 \x03(\x0b\x32$.com.airhopcomm.eson.lte.v1.PciRange\"0\n\x08PciRange\x12\x11\n\tlower_pci\x18\x01 \x01(\r\x12\x11\n\tupper_pci\x18\x02 \x01(\r\"G\n\x0cNeighborList\x12\x37\n\tneighbors\x18\x01 \x03(\x0b\x32$.com.airhopcomm.eson.lte.v1.Neighbor\"\xde\x01\n\x08Neighbor\x12\x0c\n\x04\x65\x63gi\x18\x01 \x01(\x06\x12\x37\n\tcell_size\x18\x02 \x01(\x0e\x32$.com.airhopcomm.eson.lte.v1.CellSize\x12/\n\tdl_earfcn\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12/\n\tul_earfcn\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12)\n\x03pci\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value*\x82\x01\n\x08\x43\x65llSize\x12\x15\n\x11\x43\x45LL_SIZE_UNKNOWN\x10\x00\x12\x13\n\x0f\x43\x45LL_SIZE_FEMTO\x10\x01\x12\x18\n\x14\x43\x45LL_SIZE_ENTERPRISE\x10\x02\x12\x1b\n\x17\x43\x45LL_SIZE_OUTDOOR_SMALL\x10\x03\x12\x13\n\x0f\x43\x45LL_SIZE_MACRO\x10\x04\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])

_CELLSIZE = _descriptor.EnumDescriptor(
  name='CellSize',
  full_name='com.airhopcomm.eson.lte.v1.CellSize',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CELL_SIZE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CELL_SIZE_FEMTO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CELL_SIZE_ENTERPRISE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CELL_SIZE_OUTDOOR_SMALL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CELL_SIZE_MACRO', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=877,
  serialized_end=1007,
)
_sym_db.RegisterEnumDescriptor(_CELLSIZE)

CellSize = enum_type_wrapper.EnumTypeWrapper(_CELLSIZE)
CELL_SIZE_UNKNOWN = 0
CELL_SIZE_FEMTO = 1
CELL_SIZE_ENTERPRISE = 2
CELL_SIZE_OUTDOOR_SMALL = 3
CELL_SIZE_MACRO = 4



_CELL = _descriptor.Descriptor(
  name='Cell',
  full_name='com.airhopcomm.eson.lte.v1.Cell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ecgi', full_name='com.airhopcomm.eson.lte.v1.Cell.ecgi', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cell_size', full_name='com.airhopcomm.eson.lte.v1.Cell.cell_size', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dl_earfcn', full_name='com.airhopcomm.eson.lte.v1.Cell.dl_earfcn', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ul_earfcn', full_name='com.airhopcomm.eson.lte.v1.Cell.ul_earfcn', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pci', full_name='com.airhopcomm.eson.lte.v1.Cell.pci', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pci_pool', full_name='com.airhopcomm.eson.lte.v1.Cell.pci_pool', index=5,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neighbors', full_name='com.airhopcomm.eson.lte.v1.Cell.neighbors', index=6,
      number=1000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vendor_info', full_name='com.airhopcomm.eson.lte.v1.Cell.vendor_info', index=7,
      number=2000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=461,
)


_PCIPOOL = _descriptor.Descriptor(
  name='PciPool',
  full_name='com.airhopcomm.eson.lte.v1.PciPool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ranges', full_name='com.airhopcomm.eson.lte.v1.PciPool.ranges', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=526,
)


_PCIRANGE = _descriptor.Descriptor(
  name='PciRange',
  full_name='com.airhopcomm.eson.lte.v1.PciRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower_pci', full_name='com.airhopcomm.eson.lte.v1.PciRange.lower_pci', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper_pci', full_name='com.airhopcomm.eson.lte.v1.PciRange.upper_pci', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=576,
)


_NEIGHBORLIST = _descriptor.Descriptor(
  name='NeighborList',
  full_name='com.airhopcomm.eson.lte.v1.NeighborList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='neighbors', full_name='com.airhopcomm.eson.lte.v1.NeighborList.neighbors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=578,
  serialized_end=649,
)


_NEIGHBOR = _descriptor.Descriptor(
  name='Neighbor',
  full_name='com.airhopcomm.eson.lte.v1.Neighbor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ecgi', full_name='com.airhopcomm.eson.lte.v1.Neighbor.ecgi', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cell_size', full_name='com.airhopcomm.eson.lte.v1.Neighbor.cell_size', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dl_earfcn', full_name='com.airhopcomm.eson.lte.v1.Neighbor.dl_earfcn', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ul_earfcn', full_name='com.airhopcomm.eson.lte.v1.Neighbor.ul_earfcn', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pci', full_name='com.airhopcomm.eson.lte.v1.Neighbor.pci', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=874,
)

_CELL.fields_by_name['cell_size'].enum_type = _CELLSIZE
_CELL.fields_by_name['dl_earfcn'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_CELL.fields_by_name['ul_earfcn'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_CELL.fields_by_name['pci'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_CELL.fields_by_name['pci_pool'].message_type = _PCIPOOL
_CELL.fields_by_name['neighbors'].message_type = _NEIGHBORLIST
_CELL.fields_by_name['vendor_info'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_PCIPOOL.fields_by_name['ranges'].message_type = _PCIRANGE
_NEIGHBORLIST.fields_by_name['neighbors'].message_type = _NEIGHBOR
_NEIGHBOR.fields_by_name['cell_size'].enum_type = _CELLSIZE
_NEIGHBOR.fields_by_name['dl_earfcn'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_NEIGHBOR.fields_by_name['ul_earfcn'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_NEIGHBOR.fields_by_name['pci'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
DESCRIPTOR.message_types_by_name['Cell'] = _CELL
DESCRIPTOR.message_types_by_name['PciPool'] = _PCIPOOL
DESCRIPTOR.message_types_by_name['PciRange'] = _PCIRANGE
DESCRIPTOR.message_types_by_name['NeighborList'] = _NEIGHBORLIST
DESCRIPTOR.message_types_by_name['Neighbor'] = _NEIGHBOR
DESCRIPTOR.enum_types_by_name['CellSize'] = _CELLSIZE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cell = _reflection.GeneratedProtocolMessageType('Cell', (_message.Message,), {
  'DESCRIPTOR' : _CELL,
  '__module__' : 'lte_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.lte.v1.Cell)
  })
_sym_db.RegisterMessage(Cell)

PciPool = _reflection.GeneratedProtocolMessageType('PciPool', (_message.Message,), {
  'DESCRIPTOR' : _PCIPOOL,
  '__module__' : 'lte_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.lte.v1.PciPool)
  })
_sym_db.RegisterMessage(PciPool)

PciRange = _reflection.GeneratedProtocolMessageType('PciRange', (_message.Message,), {
  'DESCRIPTOR' : _PCIRANGE,
  '__module__' : 'lte_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.lte.v1.PciRange)
  })
_sym_db.RegisterMessage(PciRange)

NeighborList = _reflection.GeneratedProtocolMessageType('NeighborList', (_message.Message,), {
  'DESCRIPTOR' : _NEIGHBORLIST,
  '__module__' : 'lte_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.lte.v1.NeighborList)
  })
_sym_db.RegisterMessage(NeighborList)

Neighbor = _reflection.GeneratedProtocolMessageType('Neighbor', (_message.Message,), {
  'DESCRIPTOR' : _NEIGHBOR,
  '__module__' : 'lte_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.lte.v1.Neighbor)
  })
_sym_db.RegisterMessage(Neighbor)


# @@protoc_insertion_point(module_scope)
