# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nr_mlb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nr_mlb.proto',
  package='com.airhopcomm.eson.nr.mlb.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cnr_mlb.proto\x12\x1d\x63om.airhopcomm.eson.nr.mlb.v1\x1a\x1egoogle/protobuf/wrappers.proto\"$\n\x10SubscribeRequest\x12\x10\n\x08ncgi_set\x18\x01 \x03(\x06\"=\n\x15ReportCapacityRequest\x12\x0c\n\x04ncgi\x18\x01 \x01(\x06\x12\x16\n\x0e\x63\x61pacity_value\x18\x02 \x01(\r\"\x18\n\x16ReportCapacityResponse\"T\n\x07Message\x12\x42\n\nchange_req\x18\x01 \x01(\x0b\x32,.com.airhopcomm.eson.nr.mlb.v1.ChangeRequestH\x00\x42\x05\n\x03msg\"\x8f\x01\n\rChangeRequest\x12\x0c\n\x04ncgi\x18\x01 \x01(\x06\x12\x15\n\rneighbor_ncgi\x18\x02 \x01(\x06\x12)\n\x03\x63io\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12.\n\x08q_offset\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\"\x96\x01\n\x14\x43onfirmChangeRequest\x12\x0c\n\x04ncgi\x18\x01 \x01(\x06\x12\x15\n\rneighbor_ncgi\x18\x02 \x01(\x06\x12)\n\x03\x63io\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12.\n\x08q_offset\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\"\x17\n\x15\x43onfirmChangeResponse2\xf5\x02\n\nMlbService\x12h\n\tSubscribe\x12/.com.airhopcomm.eson.nr.mlb.v1.SubscribeRequest\x1a&.com.airhopcomm.eson.nr.mlb.v1.Message\"\x00\x30\x01\x12\x7f\n\x0eReportCapacity\x12\x34.com.airhopcomm.eson.nr.mlb.v1.ReportCapacityRequest\x1a\x35.com.airhopcomm.eson.nr.mlb.v1.ReportCapacityResponse\"\x00\x12|\n\rConfirmChange\x12\x33.com.airhopcomm.eson.nr.mlb.v1.ConfirmChangeRequest\x1a\x34.com.airhopcomm.eson.nr.mlb.v1.ConfirmChangeResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='com.airhopcomm.eson.nr.mlb.v1.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ncgi_set', full_name='com.airhopcomm.eson.nr.mlb.v1.SubscribeRequest.ncgi_set', index=0,
      number=1, type=6, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=115,
)


_REPORTCAPACITYREQUEST = _descriptor.Descriptor(
  name='ReportCapacityRequest',
  full_name='com.airhopcomm.eson.nr.mlb.v1.ReportCapacityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ncgi', full_name='com.airhopcomm.eson.nr.mlb.v1.ReportCapacityRequest.ncgi', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capacity_value', full_name='com.airhopcomm.eson.nr.mlb.v1.ReportCapacityRequest.capacity_value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=178,
)


_REPORTCAPACITYRESPONSE = _descriptor.Descriptor(
  name='ReportCapacityResponse',
  full_name='com.airhopcomm.eson.nr.mlb.v1.ReportCapacityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=204,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='com.airhopcomm.eson.nr.mlb.v1.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='change_req', full_name='com.airhopcomm.eson.nr.mlb.v1.Message.change_req', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='com.airhopcomm.eson.nr.mlb.v1.Message.msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=206,
  serialized_end=290,
)


_CHANGEREQUEST = _descriptor.Descriptor(
  name='ChangeRequest',
  full_name='com.airhopcomm.eson.nr.mlb.v1.ChangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ncgi', full_name='com.airhopcomm.eson.nr.mlb.v1.ChangeRequest.ncgi', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neighbor_ncgi', full_name='com.airhopcomm.eson.nr.mlb.v1.ChangeRequest.neighbor_ncgi', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cio', full_name='com.airhopcomm.eson.nr.mlb.v1.ChangeRequest.cio', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_offset', full_name='com.airhopcomm.eson.nr.mlb.v1.ChangeRequest.q_offset', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=436,
)


_CONFIRMCHANGEREQUEST = _descriptor.Descriptor(
  name='ConfirmChangeRequest',
  full_name='com.airhopcomm.eson.nr.mlb.v1.ConfirmChangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ncgi', full_name='com.airhopcomm.eson.nr.mlb.v1.ConfirmChangeRequest.ncgi', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neighbor_ncgi', full_name='com.airhopcomm.eson.nr.mlb.v1.ConfirmChangeRequest.neighbor_ncgi', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cio', full_name='com.airhopcomm.eson.nr.mlb.v1.ConfirmChangeRequest.cio', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_offset', full_name='com.airhopcomm.eson.nr.mlb.v1.ConfirmChangeRequest.q_offset', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=589,
)


_CONFIRMCHANGERESPONSE = _descriptor.Descriptor(
  name='ConfirmChangeResponse',
  full_name='com.airhopcomm.eson.nr.mlb.v1.ConfirmChangeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=614,
)

_MESSAGE.fields_by_name['change_req'].message_type = _CHANGEREQUEST
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['change_req'])
_MESSAGE.fields_by_name['change_req'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
_CHANGEREQUEST.fields_by_name['cio'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_CHANGEREQUEST.fields_by_name['q_offset'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_CONFIRMCHANGEREQUEST.fields_by_name['cio'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_CONFIRMCHANGEREQUEST.fields_by_name['q_offset'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['ReportCapacityRequest'] = _REPORTCAPACITYREQUEST
DESCRIPTOR.message_types_by_name['ReportCapacityResponse'] = _REPORTCAPACITYRESPONSE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['ChangeRequest'] = _CHANGEREQUEST
DESCRIPTOR.message_types_by_name['ConfirmChangeRequest'] = _CONFIRMCHANGEREQUEST
DESCRIPTOR.message_types_by_name['ConfirmChangeResponse'] = _CONFIRMCHANGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'nr_mlb_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.nr.mlb.v1.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

ReportCapacityRequest = _reflection.GeneratedProtocolMessageType('ReportCapacityRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPORTCAPACITYREQUEST,
  '__module__' : 'nr_mlb_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.nr.mlb.v1.ReportCapacityRequest)
  })
_sym_db.RegisterMessage(ReportCapacityRequest)

ReportCapacityResponse = _reflection.GeneratedProtocolMessageType('ReportCapacityResponse', (_message.Message,), {
  'DESCRIPTOR' : _REPORTCAPACITYRESPONSE,
  '__module__' : 'nr_mlb_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.nr.mlb.v1.ReportCapacityResponse)
  })
_sym_db.RegisterMessage(ReportCapacityResponse)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'nr_mlb_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.nr.mlb.v1.Message)
  })
_sym_db.RegisterMessage(Message)

ChangeRequest = _reflection.GeneratedProtocolMessageType('ChangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHANGEREQUEST,
  '__module__' : 'nr_mlb_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.nr.mlb.v1.ChangeRequest)
  })
_sym_db.RegisterMessage(ChangeRequest)

ConfirmChangeRequest = _reflection.GeneratedProtocolMessageType('ConfirmChangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMCHANGEREQUEST,
  '__module__' : 'nr_mlb_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.nr.mlb.v1.ConfirmChangeRequest)
  })
_sym_db.RegisterMessage(ConfirmChangeRequest)

ConfirmChangeResponse = _reflection.GeneratedProtocolMessageType('ConfirmChangeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMCHANGERESPONSE,
  '__module__' : 'nr_mlb_pb2'
  # @@protoc_insertion_point(class_scope:com.airhopcomm.eson.nr.mlb.v1.ConfirmChangeResponse)
  })
_sym_db.RegisterMessage(ConfirmChangeResponse)



_MLBSERVICE = _descriptor.ServiceDescriptor(
  name='MlbService',
  full_name='com.airhopcomm.eson.nr.mlb.v1.MlbService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=617,
  serialized_end=990,
  methods=[
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='com.airhopcomm.eson.nr.mlb.v1.MlbService.Subscribe',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReportCapacity',
    full_name='com.airhopcomm.eson.nr.mlb.v1.MlbService.ReportCapacity',
    index=1,
    containing_service=None,
    input_type=_REPORTCAPACITYREQUEST,
    output_type=_REPORTCAPACITYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConfirmChange',
    full_name='com.airhopcomm.eson.nr.mlb.v1.MlbService.ConfirmChange',
    index=2,
    containing_service=None,
    input_type=_CONFIRMCHANGEREQUEST,
    output_type=_CONFIRMCHANGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MLBSERVICE)

DESCRIPTOR.services_by_name['MlbService'] = _MLBSERVICE

# @@protoc_insertion_point(module_scope)
